version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: avito_user
      POSTGRES_PASSWORD: avito_pass
      POSTGRES_DB: avito
    volumes:
       - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
  
  # avito_api:
  #   build: .
  #   environment: 
  #     Dev: "true"
  #   ports: 
  #     - "9000:9000"
  #   depends_on: 
  #     - db